### ISSUE TITLE
different word-form-ids for identical word form data in Morpheus XML

### ISSUE THREAD

**Issue by jtauber** [gcelano/LemmatizedAncientGreekXML#1]
Not sure if this is the right place to report issues with the Morpheus XML but I found 7 cases where multiple word-form-ids are assigned to identical data.

τῷ|τω|ὁ|ο|l-s---md-|23391|the|:
    - 629708
    - 629703
τῷ|τω|τῷ|τω|d--------|33356|therefore, in this wise, thereupon|:
    - 881568
    - 881573
τῷ|τω|ὁ|ο|l-s---nd-|23391|the|:
    - 629742
    - 629737
τῷ|τω|τις|τις|p-s----d-|32709|any one, any thing, some one, some thing;|attic epic:
    - 865948
    - 865943
ᾄδω|αδω|ἀείδω|αειδω|v1spsa---|494|to sing|:
    - 14254
    - 14251
ᾄδω|αδω|ἀείδω|αειδω|v1spia---|494|to sing|:
    - 14247
    - 14244
τῷ|τω|τίς|τις|x-s----d-|32708|who? which?|attic:
    - 865805
    - 865810

**Comment by gcelano** [comment]
The Morpheus lexicon is known to contain errors. In this repository I only work on the data in the folder "texts", while keeping Morpheus as it is.

**Comment by jtauber** [comment]
@gcelano are you using the ids (either word form or lemma ids) for anything in your text files?

I'll close my two issues but wanted to make sure the errors hadn't been carried through to `texts/`
