### ISSUE TITLE
different lemma-ids for identical lemma data in Morpheus XML

### ISSUE THREAD

**Issue by jtauber** [gcelano/LemmatizedAncientGreekXML#2]
I also found 78 cases where multiple lemma-ids are assigned to identical data.

ψεύδω|ψευδω|to cheat by lies, beguile|doric:
    - 36233
    - 36232
οὐ|ου||:
    - 23810
    - 23806
θυώδης|θυωδης|smelling of incense, sweet-smelling|:
    - 15592
    - 15593
ὑγιαίνω|υγιαινω|to be sound, healthy|attic epic ionic:
    - 33380
    - 33379
ψιλόω|ψιλοω|to strip bare|attic ionic:
    - 36275
    - 36274
οὐ|ου|not|:
    - 23879
    - 23868
ψιλόω|ψιλοω|to strip bare|doric:
    - 36275
    - 36274
δρῦς|δρυς|a tree|:
    - 8907
    - 8908
πλάθω|πλαθω|to approach, draw near|doric poetic:
    - 26300
    - 26299
Σκυθίζω|σκυθιζω|to behave like a Scythian|doric:
    - 29861
    - 29862
ψεύδω|ψευδω|to cheat by lies, beguile|poetic:
    - 36233
    - 36232
ψεύδω|ψευδω|to cheat by lies, beguile|attic epic:
    - 36233
    - 36232
θυώδης|θυωδης|smelling of incense, sweet-smelling|epic poetic:
    - 15592
    - 15593
θυώδης|θυωδης|smelling of incense, sweet-smelling|epic ionic:
    - 15592
    - 15593
τρύχω|τρυχω|to wear out, waste, consume|epic ionic:
    - 33227
    - 33228
ψιλόω|ψιλοω|to strip bare|epic doric:
    - 36275
    - 36274
κείω|κειω|to cleave|attic epic doric ionic:
    - 17662
    - 17663
τρύχω|τρυχω|to wear out, waste, consume|attic epic:
    - 33227
    - 33228
Συρίζω|συριζω|to speak like a Syrian|:
    - 31777
    - 31778
τρύχω|τρυχω|to wear out, waste, consume|poetic:
    - 33227
    - 33228
κειμήλιον|κειμηλιον|anything stored up as valuable, a treasure, heirloom|:
    - 17658
    - 17657
ψιλόω|ψιλοω|to strip bare|homeric ionic:
    - 36275
    - 36274
Σκυθίζω|σκυθιζω|to behave like a Scythian|epic doric:
    - 29861
    - 29862
ψεύδω|ψευδω|to cheat by lies, beguile|attic epic doric:
    - 36233
    - 36232
δυώδεκα|δυωδεκα|twelve|:
    - 9280
    - 9279
θυώδης|θυωδης|smelling of incense, sweet-smelling|attic epic doric:
    - 15592
    - 15593
ψεύδω|ψευδω|to cheat by lies, beguile|homeric ionic:
    - 36233
    - 36232
πλάθω|πλαθω|to approach, draw near|attic epic doric ionic poetic:
    - 26300
    - 26299
κείω|κειω|to cleave|poetic:
    - 17662
    - 17663
τρύχω|τρυχω|to wear out, waste, consume|attic epic doric ionic:
    - 33227
    - 33228
ὑγιαίνω|υγιαινω|to be sound, healthy|:
    - 33380
    - 33379
ψιλόω|ψιλοω|to strip bare|epic parad_form:
    - 36275
    - 36274
ὑγιαίνω|υγιαινω|to be sound, healthy|doric:
    - 33380
    - 33379
ψεύδω|ψευδω|to cheat by lies, beguile|doric aeolic poetic:
    - 36233
    - 36232
τρύχω|τρυχω|to wear out, waste, consume|homeric ionic:
    - 33227
    - 33228
ὑγιαίνω|υγιαινω|to be sound, healthy|attic epic:
    - 33380
    - 33379
κείω|κειω|to cleave|:
    - 17662
    - 17663
ψιλόω|ψιλοω|to strip bare|doric aeolic:
    - 36275
    - 36274
ψεύδω|ψευδω|to cheat by lies, beguile|:
    - 36233
    - 36232
θυώδης|θυωδης|smelling of incense, sweet-smelling|epic doric ionic aeolic:
    - 15592
    - 15593
Συρίζω|συριζω|to speak like a Syrian|epic doric:
    - 31777
    - 31778
τρέχνος|τρεχνος|a twig|:
    - 32917
    - 32916
ψεύδω|ψευδω|to cheat by lies, beguile|doric aeolic:
    - 36233
    - 36232
Σκυθίζω|σκυθιζω|to behave like a Scythian|:
    - 29861
    - 29862
ψιλόω|ψιλοω|to strip bare|parad_form:
    - 36275
    - 36274
οὐ|ου||attic epic:
    - 23810
    - 23806
ψιλόω|ψιλοω|to strip bare|:
    - 36275
    - 36274
ὑγιαίνω|υγιαινω|to be sound, healthy|attic epic doric:
    - 33380
    - 33379
πλάθω|πλαθω|to approach, draw near|attic epic doric ionic:
    - 26300
    - 26299
ὑγιαίνω|υγιαινω|to be sound, healthy|attic epic doric ionic aeolic:
    - 33380
    - 33379
τρύχω|τρυχω|to wear out, waste, consume|:
    - 33227
    - 33228
ὑγιαίνω|υγιαινω|to be sound, healthy|attic epic doric ionic:
    - 33380
    - 33379
ψεύδω|ψευδω|to cheat by lies, beguile|epic:
    - 36233
    - 36232
ψεύδω|ψευδω|to cheat by lies, beguile|epic poetic:
    - 36233
    - 36232
κείω|κειω|to cleave|epic:
    - 17662
    - 17663
ψιλόω|ψιλοω|to strip bare|aeolic:
    - 36275
    - 36274
ψιλόω|ψιλοω|to strip bare|epic ionic:
    - 36275
    - 36274
τρύχω|τρυχω|to wear out, waste, consume|attic epic ionic:
    - 33227
    - 33228
Συρίζω|συριζω|to speak like a Syrian|doric:
    - 31777
    - 31778
ψιλόω|ψιλοω|to strip bare|epic:
    - 36275
    - 36274
ψεύδω|ψευδω|to cheat by lies, beguile|attic epic ionic:
    - 36233
    - 36232
κείω|κειω|to cleave|attic epic doric:
    - 17662
    - 17663
πλάθω|πλαθω|to approach, draw near|attic epic:
    - 26300
    - 26299
ταῦ|ταυ||:
    - 32208
    - 32207
θυώδης|θυωδης|smelling of incense, sweet-smelling|doric aeolic:
    - 15592
    - 15593
οὐ|ου|not|attic epic:
    - 23879
    - 23868
ψεύδω|ψευδω|to cheat by lies, beguile|epic doric ionic aeolic:
    - 36233
    - 36232
θυώδης|θυωδης|smelling of incense, sweet-smelling|attic epic:
    - 15592
    - 15593
κείω|κειω|to cleave|homeric ionic:
    - 17662
    - 17663
πλάθω|πλαθω|to approach, draw near|:
    - 26300
    - 26299
ψιλόω|ψιλοω|to strip bare|attic epic ionic:
    - 36275
    - 36274
οὐ|ου||epic ionic:
    - 23810
    - 23806
ὑγιαίνω|υγιαινω|to be sound, healthy|epic doric aeolic:
    - 33380
    - 33379
ψιλόω|ψιλοω|to strip bare|doric aeolic poetic:
    - 36275
    - 36274
ψεύδω|ψευδω|to cheat by lies, beguile|attic epic doric ionic:
    - 36233
    - 36232
οὐ|ου|not|epic ionic:
    - 23879
    - 23868
ψεύδω|ψευδω|to cheat by lies, beguile|epic doric aeolic:
    - 36233
    - 36232
Συρίζω|συριζω|to speak like a Syrian|attic epic doric:
    - 31777
    - 31778

**Comment by jtauber** [comment]
Interestingly, this drops to 17 if I ignore dialect.

θυώδης|θυωδης|smelling of incense, sweet-smelling:
    - 15593
    - 15592
τρέχνος|τρεχνος|a twig:
    - 32917
    - 32916
τρύχω|τρυχω|to wear out, waste, consume:
    - 33228
    - 33227
ψιλόω|ψιλοω|to strip bare:
    - 36274
    - 36275
ὑγιαίνω|υγιαινω|to be sound, healthy:
    - 33380
    - 33379
Σκυθίζω|σκυθιζω|to behave like a Scythian:
    - 29861
    - 29862
πλάθω|πλαθω|to approach, draw near:
    - 26300
    - 26299
ταῦ|ταυ|:
    - 32208
    - 32207
οὐ|ου|:
    - 23810
    - 23806
ψεύδω|ψευδω|to cheat by lies, beguile:
    - 36232
    - 36233
ἄν|αν|:
    - 2098
    - 2097
οὐ|ου|not:
    - 23879
    - 23868
Συρίζω|συριζω|to speak like a Syrian:
    - 31777
    - 31778
δρῦς|δρυς|a tree:
    - 8908
    - 8907
κειμήλιον|κειμηλιον|anything stored up as valuable, a treasure, heirloom:
    - 17657
    - 17658
κείω|κειω|to cleave:
    - 17663
    - 17662
δυώδεκα|δυωδεκα|twelve:
    - 9279
    - 9280

**Comment by jtauber** [comment]
24 if the first character of the pos is included:

ὑγιαίνω|υγιαινω|to be sound, healthy|t:
    - 33379
    - 33380
ψεύδω|ψευδω|to cheat by lies, beguile|v:
    - 36233
    - 36232
τρέχνος|τρεχνος|a twig|n:
    - 32916
    - 32917
οὐ|ου||d:
    - 23806
    - 23810
δυώδεκα|δυωδεκα|twelve|x:
    - 9279
    - 9280
ὑγιαίνω|υγιαινω|to be sound, healthy|v:
    - 33379
    - 33380
ψιλόω|ψιλοω|to strip bare|t:
    - 36274
    - 36275
τρύχω|τρυχω|to wear out, waste, consume|v:
    - 33227
    - 33228
ψιλόω|ψιλοω|to strip bare|v:
    - 36274
    - 36275
δρῦς|δρυς|a tree|n:
    - 8907
    - 8908
πλάθω|πλαθω|to approach, draw near|t:
    - 26299
    - 26300
Συρίζω|συριζω|to speak like a Syrian|t:
    - 31777
    - 31778
οὐ|ου|not|d:
    - 23868
    - 23879
τρύχω|τρυχω|to wear out, waste, consume|t:
    - 33227
    - 33228
θυώδης|θυωδης|smelling of incense, sweet-smelling|a:
    - 15593
    - 15592
ταῦ|ταυ||x:
    - 32207
    - 32208
ψεύδω|ψευδω|to cheat by lies, beguile|t:
    - 36233
    - 36232
κείω|κειω|to cleave|v:
    - 17662
    - 17663
Σκυθίζω|σκυθιζω|to behave like a Scythian|v:
    - 29862
    - 29861
δυώδεκα|δυωδεκα|twelve|m:
    - 9279
    - 9280
Συρίζω|συριζω|to speak like a Syrian|v:
    - 31777
    - 31778
κειμήλιον|κειμηλιον|anything stored up as valuable, a treasure, heirloom|n:
    - 17657
    - 17658
πλάθω|πλαθω|to approach, draw near|v:
    - 26299
    - 26300
κείω|κειω|to cleave|t:
    - 17662
    - 17663

**Comment by gcelano** [comment]
In this repository Morpheus is taken as it is, without modifications. I am not sure if anyone is actively trying to correct it, but I guess the following link is the right place for that:

https://github.com/PerseusDL/morpheus/issues

**Comment by jtauber** [comment]
I mostly wanted to make sure the errors weren't carried over to your `texts/`. If they aren't, I won't worry about it. I think the _new_ morphology in the Scaife Viewer will be driven by your `texts/` files anyway.
